name: 24-7 YouTube Live Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Download Large Video from Google Drive
      run: |
        curl -c cookies.txt -to-stdout "https://docs.google.com/uc?export=download&id=1KycKzuY8YIkpi4XIC9MC2LpAAO4OThJY" > /dev/null
        CONFIRM=$(curl -b cookies.txt -to-stdout "https://docs.google.com/uc?export=download&id=1KycKzuY8YIkpi4XIC9MC2LpAAO4OThJY" | grep -o 'confirm=[^&]*' | head -n 1)
        curl -L -b cookies.txt "https://docs.google.com/uc?export=download&${CONFIRM}&id=1KycKzuY8YIkpi4XIC9MC2LpAAO4OThJY" -o video.mp4

    - name: Start Live Stream Loop
      run: |
        ffmpeg -stream_loop -1 -re -i video.mp4 -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
